spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/greenhand?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: myFirstDemo
server:
  port: 9999
  servlet:
    context-path: /security
tomcat:
  remote-ip-header: x-forward-for
  uri-encoding: UTF-8
  max-threads: 10
  background-processor-delay: 30
#here is the importance configs of JWT
jwt:
  route:
    authentication:
      path: /auth
  header: Authorization
  expiration: 604800
  secret: zhangzhaojun

